name: ðŸ“¦ Artifact Pass
on: { workflow_dispatch: {} }
jobs:
  build:
    runs-on: ubuntu-linux
    steps:
      - run: echo "hello world" > test.txt
      - uses: actions/upload-artifact@v4
        with: { name: bundle, path: test.txt }

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with: { name: bundle }
      - run: cat info.txt
